{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gmdh.fullname" . }}-ollama
spec:
  selector:
    app.kubernetes.io/component: ollama
  ports:
    - port: 11434
      targetPort: 11434
{{- end }}
